- platform: template
  sensors:
    humans_home:
      friendly_name: Humans Home
      device_class: presence
      value_template: >
        {{ is_state('device_tracker.max_smartphone', 'home') or
            is_state('device_tracker.theresa_smartphone', 'home') }}