- platform: template
  lights:
    kitchen_leds:
      entity_id: switch.kitchen
      friendly_name: Küchen LEDs
      turn_on:
        service: switch.turn_on
        data:
          entity_id: switch.kitchen
      turn_off:
        service: switch.turn_off
        data:
          entity_id: switch.kitchen

- platform: group
  name: Kitchen Group
  entities:
    - light.kuche
    - light.kitchen_leds
    
- platform: group
  name: Wohnraum
  entities:
    - light.wohnzimmer
    - light.esstisch
    - light.leselampe
    - light.kitchen_group
    - light.deckenlampe