esphomeyaml:
  name: table_leds
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.178.198
    gateway: 192.168.178.1
    subnet: 255.255.255.0
  # power_save_mode: true  # https://esphome.io/components/wifi.html#wifi-power-save-mode

debug:
# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

switch:
- platform: gpio
  name: "Living Room Dehumidifier"
  pin: 5

mqtt:
  broker: !secret mqtt_ip