- alias: "Media: TV on -> Soundbar on"
  id: tv_on__soundbar_on
  trigger:
    platform: state
    entity_id: device_tracker.tv
    from: not_home
    to: home
  action:
  - delay: 00:00:15
  - service: media_player.turn_on
    data:
      entity_id: media_player.soundbar
  - delay: 00:00:15
  - service: media_player.select_source
    data:
      entity_id: media_player.soundbar
      source: TV

      
- alias: "Media: TV on -> Spotify off"
  id: tv_on__spotify_off
  trigger:
    platform: state
    entity_id: device_tracker.tv
    from: not_home
    to: home
  action:
    service: media_player.media_pause
    data:
      entity_id: media_player.spotify


- alias: "Media: Spotify @Wohnzimmer -> Soundbar Bluetooth"
  id: spotify_on__soundbar_bluetooth
  trigger:
  - platform: state
    entity_id: media_player.spotify
    to: playing
  - platform: state
    entity_id: sensor.spotify_source
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: media_player.soundbar
      state: 'off'
    - condition: template
      value_template: '{{ states.sensor.spotify_source.state in ["Echo Wohnzimmer",
        "Alle Lautsprecher"] }}'
    - condition: state
      entity_id: media_player.spotify
      state: playing
  action:
    service: script.turn_on
    entity_id: script.turn_on_soundbar_bluetooth


- alias: "Media: Spotify @Wohnzimmer aus -> Soundbar off"
  id: spotify_off__soundbar_off
  trigger:
    platform: state
    entity_id: media_player.spotify
    to: paused
    for:
      minutes: 5
  condition:
    condition: and
    conditions:
    # - condition: template
    #   value_template: '{{ states.media_player.soundbar.attribute.source == "Bluetooth
    #     Audio" }}'
    - condition: state
      entity_id: device_tracker.tv
      state: not_home
  action:
  - service: media_player.turn_off
    data:
      entity_id: media_player.soundbar


- alias: "Media: Dinner Scene -> Music"
  trigger:
    platform: event
    event_type: call_service
    event_data:
      service_data:
        entity_id: scene.dinner
      domain: scene
      service: turn_on
  action:
  - service: media_player.select_source
    data:
      entity_id: media_player.spotify
      source: Echo Wohnzimmer
  - service: script.turn_on
    entity_id: script.play_romantic_music
  id: 9ff5bf4cd0924633b77fcb196fe44139


- alias: "Media: Noone home -> Soundbar off"
  id: '1550734787910'
  trigger:
  - entity_id: binary_sensor.humans_home
    for: 00:15:00
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      entity_id: media_player.soundbar
    service: homeassistant.turn_off
