- alias: Device (MacBook) turned on, while Max was away
  id: laptop_on__while_max_away
  trigger:
    platform: state
    entity_id: device_tracker.max_laptop
    from: not_home
    to: home
    for:
      hours: 0
      minutes: 5
      seconds: 0
  condition:
  - condition: state
    entity_id: device_tracker.max_smartphone
    state: not_home
  action:
    service: notify.pushbullet_max
    data:
      title: Laptop turned on
      message: MacBook was turned on and Max is not home


- alias: Update Available Notification
  trigger:
    platform: state
    entity_id: updater.updater
  action:
    service: persistent_notification.create
    data:
      title: Update verfügbar
      message: Take a look at the [release notes](https://github.com/home-assistant/home-assistant/releases)
  id: d7648b1670b74d289bcf7f7b0adc7b97


- alias: Theresa Arrives -> Notify Max
  id: theresa_arrives__notify_max
  trigger:
    platform: state
    entity_id: device_tracker.theresa_smartphone
    from: not_home
    to: home
  condition:
    condition: and
    conditions:
    - condition: time
      after: '12:00:00'
      before: 05:00:00
    - condition: state
      entity_id: device_tracker.max_smartphone
      state: not_home
  action:
    service: notify.pushbullet_max
    data:
      title: Theresa ist jetzt Zuhause
      message: Theresa ist gleich Zuhause


- alias: Device (TheBeast) turned on, while Max was away
  id: thebeast_on__while_max_away
  trigger:
    platform: state
    entity_id: device_tracker.thebeast
    from: not_home
    to: home
    for:
      hours: 0
      minutes: 5
      seconds: 0
  condition:
  - condition: state
    entity_id: device_tracker.max_smartphone
    state: not_home
  action:
    service: notify.pushbullet_max
    data:
      title: TheBeast turned on
      message: TheBeast was turned on and Max is not home



- alias: High Humidty Notification
  trigger:
    platform: numeric_state
    entity_id: sensor.living_room_climate_humidity, sensor.bathroom_climate_humidity
    above: 55
    for:
      hours: 0
      minutes: 5
      seconds: 0
  condition:
  - condition: state
    entity_id: binary_sensor.humans_home
    state: 'on'
  action:
    - service: notify.pushbullet_max
      data_template:
        title: Luftfeuchtigkeitswarnung
        message: '{{ trigger.to_state.state }}% - {{ trigger.to_state.attributes.friendly_name }}'
    - service: notify.pushbullet_theresa
      data_template:
        title: Luftfeuchtigkeitswarnung
        message: '{{ trigger.to_state.state }}% - {{ trigger.to_state.attributes.friendly_name }}'



- alias: 'Sensor Low Battery Notification'
  trigger:
    - platform: numeric_state
      entity_id: sensor.living_room_climate_battery
      below: 10
    - platform: numeric_state
      entity_id: sensor.bathroom_climate_battery
      below: 10
  action:
    service: notify.pushbullet_max
    data:
      title: Sensor Low Battery Warning
      message: "Es gibt Sensoren mit < 10% Batterie"
